

-- Create the user.
DROP USER kpb23 CASCADE;
GRANT 
	CONNECT,
	CREATE TABLE,
	CREATE SESSION,
	CREATE SEQUENCE,
	CREATE VIEW,
	CREATE MATERIALIZED VIEW,
	CREATE PROCEDURE,
	CREATE TRIGGER,
	UNLIMITED TABLESPACE
	TO kpb23
	IDENTIFIED BY bjarne;

    
DROP DIRECTORY dpump_dirl;
CREATE DIRECTORY dpump_dirl as 'C:\Users\Kristofer\Desktop\Spring2017\cs342\project\datapump';
GRANT READ, WRITE ON DIRECTORY dpump_dirl to kpb23;